### ISSUE TITLE
Support for non-Steam games?

### ISSUE THREAD

**Issue by ElMelchizedek** [kekonn/discord-rpc-helper#43]
For example via Lutris or Bottles

**Comment by kekonn** [comment]
Lutris has built in support for Discord RPC normally and I don't use bottles. But isn't bottles just a Wine UI? In that case you could use https://github.com/LeadRDRK/wine-rpc I guess.

EDIT: I meant this one instead of my last link, but I'll leave both up in case both are helpfull: https://github.com/0e4ef622/wine-discord-ipc-bridge .
