### ISSUE TITLE
Shutting down I/O loop due to Discord close request reason=Invalid Client ID

### ISSUE THREAD

**Issue by walidkorchi** [kekonn/discord-rpc-helper#65]
I'm not sure what is exactly the Client ID that is asking me, the only thing I'm thinking of is this one:

![image](https://github.com/kekonn/discord-rpc-helper/assets/87608619/a8da7891-fa9c-40d4-916e-cdcc39840610)

yet it doesn't seem to work, what's hapenning?

**Comment by kekonn** [comment]
You need to register a [Discord developer account](https://discord.com/login?redirect_to=%2Fdevelopers%2Fapplications) and create your own Discord application. Under the OAuth 2 section, you can find a Client ID.

I don't think I can include mine, since I never sought official approval from Discord. But maybe that's not necessary for these kinds of applications.
